version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 vaysedshop.wsgi:application
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static/images:/app/static/images
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - DEBUG=${DEBUG}      
      - ALLOWED_HOSTS=${ALLOWED_HOSTS} 
      - MONOBANK_API_TOKEN=${MONOBANK_API_TOKEN}
    env_file:
      - .env