# Generated by Django 5.1.6 on 2025-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_main_image_and_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monobank_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
